from .alternativa import Alternativa
from .pergunta import Pergunta
from .perguntadiscursiva import PerguntaDiscursiva
from .perguntamultiplaescolha import PerguntaMultiplaEscolha
from .questionario import Questionario
from .resposta import Resposta
from .respostadiscursiva import RespostaDiscursiva
from .respostaobjetiva import RespostaObjetiva
from .tentativaquestionario import TentativaQuestionario